// Augments the `CloudflareEnv` interface (bindings live in
// worker-configuration.d.ts, regenerated by `npm run cf-typegen` — see
// wrangler.jsonc) with secrets/plain env vars that aren't Cloudflare
// bindings, so they aren't picked up by `wrangler types`. Set locally in
// .dev.vars (gitignored) and in production via `wrangler secret put`.
// See .env.example for the full list.
interface CloudflareEnv {
  BETTER_AUTH_SECRET: string;
  /** Origin better-auth builds magic-link callback URLs from. */
  BETTER_AUTH_URL?: string;
  /** Origin used for portal/event links inside outgoing email; falls back to
   * BETTER_AUTH_URL. */
  APP_URL?: string;
  SENDGRID_API_KEY?: string;
  /** From identity on every outgoing email (src/lib/email.ts). The address
   * also becomes the calendar invite's ORGANIZER, so it must be a real,
   * verified sending address in production. */
  EMAIL_FROM_NAME?: string;
  EMAIL_FROM_ADDRESS?: string;
}
