// Augments the `CloudflareEnv` interface (bindings live in
// worker-configuration.d.ts, regenerated by `npm run cf-typegen` — see
// wrangler.jsonc) with secrets/plain env vars that aren't Cloudflare
// bindings, so they aren't picked up by `wrangler types`. Set locally in
// .dev.vars (gitignored) and in production via `wrangler secret put`.
// See .env.example for the full list.
interface CloudflareEnv {
  BETTER_AUTH_SECRET: string;
  /** Origin better-auth builds magic-link callback URLs from. */
  BETTER_AUTH_URL?: string;
  RESEND_API_KEY?: string;
}
